---
- name: configure apache2
  hosts: all
  tasks:
    - name: Call playbooks for apache configuration
      include_tasks: "{{item}}"
      with_items:
        - install.yml
        - edit_index.yml
        - restart.yml
        - check_apache_response.yml

...
