---
- name: Implementing handlers
  hosts: all
  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: present
        update_cache: yes
      notify: Check apache response
    - name: Edit the index.html file
      copy:
        content: "Welcome to MyWorld1"
        dest: /var/www/html/index.html
      notify: Restart apache
  handlers:
    - name: Restart apache
      service:
        name: apache2
        state: restarted
    - name: Check apache response
      uri:
        url: "{{item}}"
        status_code: 200
        with_items:
          - http://172.31.13.204
          - http://172.31.1.11
